### ISSUE TITLE
Use Mapquest map tiles instead of OSM

### ISSUE THREAD

**Issue by mishari** [oeco/opendev-wptheme#1]
The use of OSM.org tiles for the maps may be against their aup, I would suggest moving over to http://wiki.openstreetmap.org/wiki/Mapquest#MapQuest-hosted_map_tiles instead. I'll make a pull request with the appropriate changes.

**Comment by mishari** [comment]
I just realized that it's not coded into the theme itself.

**Comment by miguelpeixe** [comment]
This is a setup on the map editor, can be found on the site's dashboard
