### ISSUE TITLE
Data catalog button should lead to data.opendevelopmentmekong.net

### ISSUE THREAD

**Issue by acorbi** [oeco/opendev-wptheme#11]
![bildschirmfoto 2015-02-01 um 10 11 25](https://cloud.githubusercontent.com/assets/384894/5991630/ce433564-a9fb-11e4-8bff-8f414e959630.png)
The button "Access the complete database" pictured above and present in every DATA page of every country side, currently takes to subsite/data and should take to data.opendevelopmentmekong.net

**Comment by miguelpeixe** [comment]
The WPCKAN plugin must be configurated for this page to work. The link used is the actual CKAN homepage, from the WPCKAN plugin..

**Comment by acorbi** [comment]
To clarify: so the template of this page pulls the URL from the plugin and links that button to it automatically. Is that what you mean? @miguelpeixe In that case, please go ahead and close the Issue

**Comment by miguelpeixe** [comment]
Exactly!
