### ISSUE TITLE
Map zooms on mouse scroll although disabled

### ISSUE THREAD

**Issue by acorbi** [oeco/opendev-wptheme#15]
Reproducing on http://opendevelopmentmekong.net/
- [X] Appearance > Open Development > Disable mousewheel zooming

Maps in pages such as http://opendevelopmentmekong.net/2015/01/31/google-eyes-burgeoning-digital-revenue-in-2015/#!/story=post-370&loc=18.35452552912664,101.414794921875,7 still zoom in/out on mouse scroll

**Comment by miguelpeixe** [comment]
The settings on this page is exclusive to the "interactive map". Available using the `[odmap]` shortcode. Each map has it's own setting.

**Comment by acorbi** [comment]
Could we disable the zoom scrolling in the maps per default? That would make navigation through the site way easier. Specially on pages with maps taking big part of the screen.

**Comment by miguelpeixe** [comment]
I can disable mousewheel zoom for every map but that's irreversible. All maps will have mousewheel zoom disabled. Is that ok?

**Comment by acorbi** [comment]
I would just leave that functionality for the [+] & [-] buttons on the map. If "zoom on scrolling is enabled" there are pages that become unbrowsable like this one http://opendevelopmentmekong.net/maps/greater-mekong-subregion-hydropower-dams-2014/#!/story=post-58760&loc=-85.035941506574,-425.7421875,2 Try to scroll down to the bottom here using your favourite multi-touch device....

**Comment by miguelpeixe** [comment]
Ok, I'll disable the mousewheel by default and hide this map setting option on the child theme.

**Comment by miguelpeixe** [comment]
Fixed 3aeac38dce3c6eff97ad73879e6df1ca24205d88
Available on the new release 0.1.2
