### ISSUE TITLE
Responsive design issue on Briefing page

### ISSUE THREAD

**Issue by DBishton** [oeco/opendev-wptheme#17]
Overlap of right hand column containing contents and category text on Briefings page when an image is inserted.

Is there a setting that needs to be changed to handle this?

![image](https://cloud.githubusercontent.com/assets/1206387/6019554/6344dd32-abd4-11e4-8ad1-2f46445e16ad.png)

**Comment by miguelpeixe** [comment]
fixed 88b7ba3e8f3bd58f7fb5a699d90e66c5320c6a94
