### ISSUE TITLE
Briefings: Tableau Integration

### ISSUE THREAD

**Issue by WillieShubert** [oeco/opendev-wptheme#20]
Clicking on the embedded tableau graphics on the energy sector briefing pushes you back up the the top of the page.  

Reference: http://cambodia.opendevelopmentmekong.net/briefings/the-cambodian-energy-sector/#

**Comment by miguelpeixe** [comment]
Hey @WillieShubert 

This tableau doesn't look properly embedded. It's just an image with a link to nowhere (that's why it goes to the top of the page when you click it)

**Comment by DBishton** [comment]
Thanks Willie,

This was caused by a WP permissions issue that was removing code from posts made by users without Super-admin permissions. This permissions issue has now been resolved, and I've followed up with Pinkie to re-post the broken Tableau embed code blocks in the ODC Briefings.

**Comment by miguelpeixe** [comment]
Can we close this issue?

**Comment by WillieShubert** [comment]
Yes. It looks to be working fine.
