### ISSUE TITLE
Categories not implemented on Briefing post type

### ISSUE THREAD

**Issue by DBishton** [oeco/opendev-wptheme#21]
Currently the sidebar functionality to add categories to posts of type Briefings does not exist. We need to be able to add these categories to demonstrate categorization of content according to our taxonomy.

![image](https://cloud.githubusercontent.com/assets/1206387/6097820/81e8f6b0-affd-11e4-97ba-d9df135355dc.png)

**Comment by miguelpeixe** [comment]
fixed on a1177e83c8998812520bffa2b0450d0f1725144d and available on version 0.1.4
