### ISSUE TITLE
update version number on config

### ISSUE THREAD

**Issue by acorbi** [oeco/opendev-wptheme#24]
Current version of the theme is 0.1.6. However, while browsing the theme section on the WP Dashboard, version 0.1.1 is shown

![bildschirmfoto 2015-02-18 um 20 16 50](https://cloud.githubusercontent.com/assets/384894/6254732/25b7ddb0-b7ab-11e4-977c-c8eb7e7f3f7c.png)

**Comment by miguelpeixe** [comment]
thanks for the reminder, I'll fix it for the next release
