### ISSUE TITLE
Header menu child items hierarchy display issue

### ISSUE THREAD

**Issue by DBishton** [oeco/opendev-wptheme#25]
Child items appear to display inconsistently in the header menu with more than one child item at the same level of hierarchy. In the screenshot below, Electricity and Hydropwer are both children of Energy.

![image](https://cloud.githubusercontent.com/assets/1206387/6369702/50f7784e-bd1b-11e4-9f68-674b58dba602.png)

**Comment by WillieShubert** [comment]
This is going to be handled by including a dropdown menu feature in the dynamic bar. It will be included in the next release
