### ISSUE TITLE
Script error when accessing briefings

### ISSUE THREAD

**Issue by DBishton** [oeco/opendev-wptheme#28]
Currently accessing briefings on our PPS throws the following error:

Fatal error: Call to undefined function IsNullOrEmptyString() in /var/www/html/wp-content/themes/jeo-odm/functions.php on line 369

![image](https://cloud.githubusercontent.com/assets/1206387/6384342/e793c07e-bd8d-11e4-8806-b13ad1e6c1e9.png)

**Comment by acorbi** [comment]
The newest version of wpckan got that method renamed from **IsNullOrEmptyString** to **wpckan_is_null_or_empty_string** for consistency. I believe the theme should not make use of internal methods of any plugin and thus i suggest that the theme implements such a function itself.
@miguelpeixe I will implement this on https://github.com/OpenDevelopmentMekong/opendev-wptheme and open a Pull Request.

**Comment by miguelpeixe** [comment]
fixed ff2837f0451fc0eecfcdc39290dc4023937a8ff7
