### ISSUE TITLE
Hide individual briefing pages from home page

### ISSUE THREAD

**Issue by Numnov** [oeco/opendev-wptheme#33]
Remove briefing container from home page

**Comment by WillieShubert** [comment]
What is the rationale for this decision? This is a significant departure from the approved reference designs.

**Comment by DBishton** [comment]
The reference designs presented a container for three categories, each containing a menu of five of our top-level taxonomy topics. This requirement was communicated before those designs were developed, and confirmed upon receipt. 

This was reiterated upon receipt of the first version of the child theme, when it was communicated that a ‘list’ style presentation of individual top-level topics did not fulfill one of our core requirements. 
The rationale behind the decision to remove the container completely arose after no changes were made to the ‘list’ presentation despite communication of the need to do so. 

The interim solution we decided upon was for us to mimic this category presentation in the three ‘introductory’ tiles, and remove the listing of individual topics. This was agreed upon in our conference call on February 14, 2015, and documented in the action items circulated after that call.
