### ISSUE TITLE
Language picker should display items in appropriate unicode characters

### ISSUE THREAD

**Issue by DBishton** [oeco/opendev-wptheme#36]
Language options appearing in the header menu should be displayed in their appropriate unicode characters.

![image](https://cloud.githubusercontent.com/assets/1206387/6391383/605447ae-bde8-11e4-95a4-b1cb0b26546c.png)

**Comment by miguelpeixe** [comment]
Sorry for my ignorance on the language but, what would be the appropriate unicode characters?

**Comment by DBishton** [comment]
Hi @miguelpeixe,

I should have been more specific. Unicode characters should be included for the supported languages in the system: Thai, Khmer, Vietnamese, and Lao. Mishari will add more on this issue -- we will need to confirm that unicode sets exist for Lao and Burmese. Thanks Miguel.

**Comment by mishari** [comment]
@miguelpeixe I believe what @DBishton means is that we use the language name in their local script so that users know that it's possible to switch language, for example, the Thai option will be displayed as ไทย I will get the other languages over to you shortly after I've verified them.

**Comment by mishari** [comment]
Thai => ไทย
Vietnamese => tiếng Việt
Laos => ລາວ
Khmer => ខ្មែរ
Burmese => မြန်မာ

**Comment by miguelpeixe** [comment]
The language labels are editable through the language plugin dashboard. I can't find Khmer as an available language on the plugin. Looks like someone manually included the language, which means the label should be edited with the appropriate characters on the dashboard.

**Comment by mishari** [comment]
To elaborate on that, in mqTranslate settings, when you go to language name you will see that "Khmer" is written, that should be in local script such as ខ្មែរ so that it appears correctly. Fixed. Please close.
