### ISSUE TITLE
Adding New Map

### ISSUE THREAD

**Issue by Huyeng** [oeco/opendev-wptheme#6]
Testing http://odmekong.geojournalism.org:
Error: Searching function of the layers in adding new map doesn't work properly. 
Expected: List result of layers that are looking for.

**Comment by miguelpeixe** [comment]
It is working ok here. We had a feel problems with the wpckan plugin breaking the dashboard javascript a few days ago but this is already fixed. Can you try again and report me a more specific error if it happens again?

**Comment by Huyeng** [comment]
It works ok now after updating the theme.
