### ISSUE TITLE
Implement distance between HL

### ISSUE THREAD

**Issue by kathi-aeviator** [oeco/opendev-wptheme#60]
![image](https://cloud.githubusercontent.com/assets/15011163/12392145/5da64402-be1f-11e5-94f0-91cbc83bec19.jpeg)

implement small distance (about 3-5px) above the HL of the sub-menus 
E.g. On this screenshot it's above "PEOPLE" and the border. So there must be more orange space.

**Comment by acorbi** [comment]
@kathi-aeviator wrong repository, please move to http://github.com/OpenDevelopmentMekong/opendev-wptheme

**Comment by kathi-aeviator** [comment]
Yes. Close issue.
